### ISSUE TITLE
Update link to "YSFlight Wiki"

### ISSUE THREAD

**Issue by ghost** [YSFHQ/phpbb#13]
> On August 15, 2018, Wikia announced it would fully change its domain name into `fandom.com` in early 2019. Various Wikis were tested with the new domain during 2018, with Wikia confirming that the process would be completed by February 4, 2019, with the exception of wikis that focused on "more serious topics", which would instead have their domains changed to `wikia.org` instead of `fandom.com`. The process was delayed by a few weeks due to issues with Google adverts, but was properly completed on February 22, 2019.

Update link to "YSFlight Wiki" (on side bar and where its needed too):

- legacy wiki link: ~~https://ysflightsim.wikia.com/~~
  - **actual wiki link:** https://ysflightsim.fandom.com/

### REFERENCE

- https://en.wikipedia.org/wiki/Fandom_(website)
  - https://en.wikipedia.org/wiki/Fandom_(website)#2016%E2%80%932018:_Fandom_brand

**Comment by EricTendian** [comment]
Thanks, just updated the sidebar with the new link.
