### ISSUE TITLE
Extend search for aircraft type names (2-5 character)

### ISSUE THREAD

**Issue by ghost** [YSFHQ/phpbb#14]
Actually YSFHQ Forum search can't be used for search topics by aircraft type name, for example: `U2`/`U-2`, `An2`/`AN-2`, `F16`/`F-16`, `XF-85`, etc.

- https://forum.ysfhq.com/search.php?keywords=XF-85
> The following words in your search query were ignored because they are too common words: **xf** **85**.\
> You must specify at least one word to search for. Each word must consist of at least 3 characters and must not contain more than 14 characters excluding wildcards.

**Comment by EricTendian** [comment]
I can't get it to accept small strings like U-2, but I've updated the search index so the above search XF-85 and other slightly longer keywords should work.

**Comment by ghost** [comment]
> I can't get it to accept small strings like U-2, but I've updated the search index so the above search XF-85 and other slightly longer keywords should work.

Thanks.
