### ISSUE TITLE
Dark board style

### ISSUE THREAD

**Issue by ghost** [YSFHQ/phpbb#2]
Add "YSFHQ Dark" or "YSFHQ Nightly" board style.
![darkfx](https://cloud.githubusercontent.com/assets/13188580/17875904/848a4e6e-68de-11e6-89b3-e19b3ad60dc0.png)

Links:
- http://demo.phpbb3styles.net/DarkFX
- https://www.phpbb.com/customise/db/styles/board_styles/dark-17
- http://demo.phpbb3styles.net/dark

**Comment by EricTendian** [comment]
@Symbian9 thanks for the links. If you had to choose between https://www.phpbb.com/customise/db/style/black/ and https://www.phpbb.com/customise/db/style/digi/ which would you prefer?

**Comment by ghost** [comment]
Think, try firstly this
- https://www.phpbb.com/customise/db/style/digi/

And if it will get bad support then switch to another one.
- https://forum.ysfhq.com/viewtopic.php?p=101797#p101797

P.S.: Also, it would be good if user can use own (3rd party) style, but I don't know is it possible.

**Comment by EricTendian** [comment]
Closing this as the style Digi has been installed on the forum.
