### ISSUE TITLE
Add "Cancel" button in editing post dialog

### ISSUE THREAD

**Issue by ghost** [YSFHQ/phpbb#3]
![button](https://cloud.githubusercontent.com/assets/13188580/17933548/252ea100-6a1d-11e6-8866-02524a6d682e.png)

**Comment by EricTendian** [comment]
I think the Back button would suffice in this case, and also I can't find any mods for phpBB 3.2 to add a Cancel button.

**Comment by ghost** [comment]
Look
* https://phpbb-extensions.ga/extensions/dmzx/postingresetbutton.html
* https://www.phpbb.com/customise/db/extension/posting_reset_button/

**Comment by EricTendian** [comment]
Thanks! Done.
