### ISSUE TITLE
wiki.ysfhq.com and/or wiki.ysflight.org

### ISSUE THREAD

**Issue by ghost** [YSFHQ/phpbb#4]
Propose make own wiki for YSFHQ community members knowledge on subdomain:
* http://wiki.ysfhq.com (not used yet)

As engine propose use DokuWiki (that is PHP-based):
* https://github.com/splitbrain/dokuwiki
  * https://www.dokuwiki.org/DokuWiki

Other engines
* Statistic of wiki-engines http://www.wikimatrix.org/statistic/Most+Views
* List of wiki-engines http://wiki.c2.com/?WikiEngines

Also, it would be cool add possibility login on this wiki using YSFHQ account settings (by integrating it into YSFHQ phpBB engine).
DokuWiki, as wiki at all, provide possibility create pages with tables, statistic, documentation etc.

As prototype is FlightGear community wiki
* https://wiki.flightgear.org

There is one of very usefull futures on DokuWiki - tables
* http://serverfault.com/questions/128924/creating-tables-in-dokuwiki

It will help leave GoogleDocs dependency for such topics as this:
* https://forum.ysfhq.com/viewtopic.php?p=105436#p105436
  * https://docs.google.com/spreadsheets/d/1OtwLQuQX3TOCsTeGrQeVOIJjBKNPh31UbRRzdkF1Wqc/edit

P.S.: currently there is 3rd party wiki on Wikia hosting, but it require additional registration and depend on Wikia company itself.

**Comment by EricTendian** [comment]
Per discussion in https://forum.ysfhq.com/viewtopic.php?f=217&t=9100 there is not a great enough need from the community to create a wiki hosted on YSFHQ.
