### ISSUE TITLE
vms.ysfhq.com - Virtual Airline Management

### ISSUE THREAD

**Issue by ghost** [YSFHQ/phpbb#5]
Proposed URL's (chose one from list)
* va.ysfhq.com
* vam.ysfhq.com
* vms.ysfhq.com

Engine
* https://github.com/LeCoyote/vam-contrib
* https://github.com/nabeelio/phpVMS

Other
* https://github.com/search?q=Virtual+Airline+Management&ref=searchresults&type=Code&utf8=%E2%9C%93
* https://sourceforge.net/directory/?q=virtual%20airline

**Comment by EricTendian** [comment]
There seems to be a lack of interest in this per https://forum.ysfhq.com/viewtopic.php?p=106561#p106561 so closing the issue. It's not particularly code-related either, so a request like this should be posted on the forum first.
