### ISSUE TITLE
Add link to "YSFlight OpenSource" repositories

### ISSUE THREAD

**Issue by u2fly** [YSFHQ/phpbb#7]
Add in "**Add-on Creation**" section on <a href="http://forum.ysfhq.com">main YSFHQ forum page</a> link to this repo:
* http://github.com/ysflight-opensource

In this repo will try collect near all opensource projects (or their backups), related to YSFlight Simulator.

**Comment by u2fly** [comment]
Thanks, Eric!

But need little correction: rename it from "YSFlight-related Open-Source Projects" to "**Open-Source Tools for YSFlight**" (it will look little shorten and better for understanding)

**Comment by EricTendian** [comment]
Good call. Made the update.
