### ISSUE TITLE
openys.ysfhq.com (update needed)

### ISSUE THREAD

**Issue by u2fly** [YSFHQ/phpbb#9]
Currently version of OpenYS on special page is outdated (20150226)
* https://openys.ysfhq.com/

Here are newer versions
* https://forum.ysfhq.com/viewtopic.php?p=83070#p83070

So, only fix links on openys.ysfhq.com page

**Comment by EricTendian** [comment]
The index page now redirects to the forum thread as the website is inactive. Thus everyone should get the latest version.
